# Generated by Django 4.1.1 on 2022-09-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NLPUrdu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="image")),
                (
                    "Grayscaleimage",
                    models.ImageField(
                        blank=True, null=True, upload_to="grayscale_image"
                    ),
                ),
                ("Text", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
