# Generated by Django 4.1.1 on 2022-10-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLPapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nlpurdu",
            name="Gray_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
