# Generated by Django 4.1.1 on 2022-10-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NLPapp", "0002_nlpurdu_gray_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nlpurdu", old_name="Gray_image", new_name="Grayimage",
        ),
    ]
